app:
  title: AI Studio Tech Catalog
  baseUrl: http://localhost:3000
  support:
    url: https://gitlab.com/ai-studio3/backstage/-/issues
    items:
      - title: Issues
        icon: gitlab
        links:
          - url: https://gitlab.com/ai-studio3/backstage/-/issues
            title: GitLab Issues

organization:
  name: AI Studio

backend:
  auth:
    keys:
      - secret: ${AUTH_BACKEND_SECRET}
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
  azure:
    - host: dev.azure.com
      token: ${AZURE_TOKEN}
  bitbucket:
    - host: bitbucket.org
      username: ${BITBUCKET_USERNAME}
      password: ${BITBUCKET_PASSWORD}

proxy:
  '/jenkins':
    target: 'http://your-jenkins.example.com'
    changeOrigin: true
    headers:
      Authorization: Basic ${JENKINS_AUTH}

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

scaffolder:
  defaultAuthor:
    name: Backstage Scaffolder
    email: scaffolder@backstage.io

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Domain, Group, User]
  locations:
    # Système principal AI Studio
    - type: file
      target: ../../catalog/systems/ai-studio-system.yaml
      
    # Découverte automatique des repos dans le groupe ai-studio3
    - type: gitlab-discovery
      target: https://gitlab.com/ai-studio3/*/blob/main/catalog-info.yaml
      
    # Services existants documentés
    - type: file
      target: ../../catalog/examples/entities.yaml
      
    # APIs externes utilisées par AI Studio
    - type: file
      target: ../../catalog/external-apis.yaml
      
    # Ressources et infrastructures
    - type: file
      target: ../../catalog/resources.yaml