apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{SERVICE_NAME}}-service
  title: {{SERVICE_TITLE}}
  description: {{SERVICE_DESCRIPTION}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:file:../services/{{SERVICE_NAME}}
  labels:
    system: ai-studio
    tier: backend
    framework: {{FRAMEWORK}}
    language: {{LANGUAGE}}
  tags:
    - backend
    - {{LANGUAGE}}
    - {{FRAMEWORK}}
    - microservice
spec:
  type: service
  lifecycle: production
  owner: {{TEAM}}
  system: ai-studio
  dependsOn:
    {{DEPENDENCIES}}
  providesApis:
    - {{SERVICE_NAME}}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: {{SERVICE_NAME}}-api
  title: {{SERVICE_TITLE}} API
  description: API REST pour {{SERVICE_TITLE}}
spec:
  type: openapi
  lifecycle: production
  owner: {{TEAM}}
  system: ai-studio
  definition: |
    openapi: 3.0.0
    info:
      title: {{SERVICE_TITLE}} API
      version: 1.0.0
      description: API pour {{SERVICE_TITLE}}
    servers:
      - url: http://localhost:{{PORT}}
        description: Development server
    paths:
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service opérationnel
      /ready:
        get:
          summary: Readiness check
          responses:
            '200':
              description: Service prêt