apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-mfe
  title: Authentication MFE
  description: Micro-frontend de gestion de l'authentification avec SSO et MFA
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://gitlab.com/ai-studio3/mfe/-/tree/main/auth
    backstage.io/gitlab-project-slug: ai-studio3/mfe
  labels:
    system: ai-studio
    tier: frontend
    framework: react
  tags:
    - frontend
    - react
    - nextjs
    - micro-frontend
    - typescript
spec:
  type: website
  lifecycle: production
  owner: frontend-team
  system: ai-studio
  dependsOn:
    - component:portal-shell
  providesApis:
    - auth-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  title: Authentication MFE API
  description: API pour le micro-frontend Authentication MFE
spec:
  type: openapi
  lifecycle: production
  owner: frontend-team
  system: ai-studio
  definition: |
    openapi: 3.0.0
    info:
      title: Authentication MFE API
      version: 1.0.0
      description: API pour Micro-frontend de gestion de l'authentification avec SSO et MFA
    servers:
      - url: http://localhost:3001
        description: Development server
    paths:
      /health:
        get:
          summary: Health check
          responses:
            '200':
              description: Service opérationnel
